#!/bin/bash
add()
{
	local num1
	local num2
	echo "Enter num 1:"
	read  num1
	echo "Enter num 2:"
	read  num2

	result=$((num1 + num2))
	echo "$num1 + $num2 = $result"
}

echo "This is an adding calculator"
add
